package webapp.debt.tracker.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import webapp.debt.tracker.model.DebtInfo;
import webapp.debt.tracker.repository.DebtInfoRepository;

/**
* Generated by Spring Data Generator on 10/03/2020
*/
@Service
public class DebtInfoServiceImpl implements DebtInfoService {

	private DebtInfoRepository debtInfoRepository;

	@Autowired
	public DebtInfoServiceImpl(DebtInfoRepository debtInfoRepository) {
		this.debtInfoRepository = debtInfoRepository;
	}

	@Override
	public List<DebtInfo> getDebtInfoByAppUserId(Integer appUserId) {
		// TODO Auto-generated method stub
		return debtInfoRepository.findByAppUserAppUserId(appUserId);
	}

	@Override
	@Transactional
	public DebtInfo saveDebtInfo(DebtInfo debtInfo) {
		// TODO Auto-generated method stub
		return debtInfoRepository.save(debtInfo);
	}

	@Override
	@Transactional
	public DebtInfo updateDebtInfo(DebtInfo debtInfo) {
		// TODO Auto-generated method stub
		return debtInfoRepository.save(debtInfo);
	}

	@Override
	public List<DebtInfo> getDebtInfoByDebtorId(Integer debtorId) {
		// TODO Auto-generated method stub
		return debtInfoRepository.findByDebtorInfoDebtorId(debtorId);
	}

	@Override
	public Integer getNumberOfDebtorsByAppUserId(Integer appUserId) {
		// TODO Auto-generated method stub
		return debtInfoRepository.getNumberOfDebtorsByAppUserId(appUserId);
	}

}
