package webapp.debt.tracker.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import webapp.debt.tracker.model.DebtorInfo;
import webapp.debt.tracker.repository.DebtorInfoRepository;

/**
* Generated by Spring Data Generator on 10/03/2020
*/
@Service
public class DebtorInfoServiceImpl implements DebtorInfoService {

	private DebtorInfoRepository debtorInfoRepository;

	@Autowired
	public DebtorInfoServiceImpl(DebtorInfoRepository debtorInfoRepository) {
		this.debtorInfoRepository = debtorInfoRepository;
	}

	@Override
	@Transactional
	public DebtorInfo saveDebtorInfo(DebtorInfo debtorInfo) {
		// TODO Auto-generated method stub
		return debtorInfoRepository.save(debtorInfo);
	}

	@Override
	@Transactional
	public DebtorInfo updateDebtorInfo(DebtorInfo debtorInfo) {
		// TODO Auto-generated method stub
		return debtorInfoRepository.save(debtorInfo);
	}

	@Override
	public DebtorInfo getDebtorInfoById(Integer debtorInfoId) {
		// TODO Auto-generated method stub
		return debtorInfoRepository.findById(debtorInfoId).get();
	}

//	@Override
//	public List<DebtorInfo> getAllDebtorsByAppUserId(Integer appUserId) {
//		// TODO Auto-generated method stub
//		return debtorInfoRepository.findByAppUserAppUserId(appUserId);
//	}

}
