package webapp.debt.tracker.service;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import webapp.debt.tracker.model.DebtInfo;
import webapp.debt.tracker.model.DebtPaymentDetail;
import webapp.debt.tracker.model.DebtorInfo;
import webapp.debt.tracker.repository.DebtPaymentDetailRepository;

/**
 * Generated by Spring Data Generator on 10/03/2020
 */
@Service
public class DebtPaymentDetailServiceImpl implements DebtPaymentDetailsService {

	private DebtPaymentDetailRepository debtPaymentDetailRepository;
	private DebtInfoService debtInfoService;
	private DebtorInfoService debtorInfoService;

	@Autowired
	public DebtPaymentDetailServiceImpl(DebtPaymentDetailRepository debtPaymentDetailRepository, DebtInfoService debtInfoService,
			DebtorInfoService debtorInfoService) {
		this.debtPaymentDetailRepository = debtPaymentDetailRepository;
		this.debtInfoService = debtInfoService;
		this.debtorInfoService = debtorInfoService;
	}

	@Override
	public List<DebtPaymentDetail> getDebtPaymentDetailsByDebtInfoId(Integer debtInfoId) {
		return debtPaymentDetailRepository.findByDebtInfoDebtInfoId(debtInfoId);
	}

	@Override
	@Transactional
	public DebtPaymentDetail saveDebtPaymentDetail(DebtPaymentDetail debtPaymentDetail, DebtInfo debtInfo,
			DebtorInfo debtorInfo) {
		// TODO Auto-generated method stub
		debtorInfoService.saveDebtorInfo(debtorInfo);
		debtInfoService.saveDebtInfo(debtInfo);
		return debtPaymentDetailRepository.save(debtPaymentDetail);
	}

	@Override
	@Transactional
	public DebtPaymentDetail updateDebtPaymentDetail(DebtPaymentDetail debtPaymentDetail) {
		// TODO Auto-generated method stub
		return debtPaymentDetailRepository.save(debtPaymentDetail);
	}

	@Override
	public List<DebtPaymentDetail> getDebtPaymentPassPaymentDateAndPending(Integer appUserId) {
		// TODO Auto-generated method stub
		return debtPaymentDetailRepository.getDebtPaymentPassPaymentDateAndPending(appUserId);
	}

	@Override
	public List<DebtPaymentDetail> getDebtPaymentPassPaymentDateAndPaid(Integer appUserId) {
		// TODO Auto-generated method stub
		return debtPaymentDetailRepository.getDebtPaymentPassPaymentDateAndPaid(appUserId);
	}

}
