package webapp.debt.tracker.repository;

import java.util.Optional;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
import webapp.debt.tracker.model.AppUser;

/**
* Generated by Spring Data Generator on 10/03/2020
*/
@Repository
public interface AppUserRepository extends CrudRepository<AppUser, Integer> {
	
	
	Optional<AppUser> findByUserName(String userName);
	Optional<AppUser> findByEmailAddress(String userEmail);
	
}
