package webapp.debt.tracker.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import webapp.debt.tracker.model.DebtInfo;

/**
 * Generated by Spring Data Generator on 10/03/2020
 */
@Repository
public interface DebtInfoRepository extends CrudRepository<DebtInfo, Integer> {

	List<DebtInfo> findByAppUserAppUserId(Integer appUserId);

	
	List<DebtInfo> findByDebtorInfoDebtorId(Integer debtorId);

	@Query(value = "select count(distinct (debtor_data_id)) from debt_tracker.debt_info  where app_user_id = :appUserId", nativeQuery = true)
	Integer getNumberOfDebtorsByAppUserId(@Param("appUserId") Integer appUserId);
}
