package webapp.debt.tracker.repository;

import java.util.List;
import java.util.Optional;

import org.springframework.data.repository.CrudRepository;
import org.springframework.stereotype.Repository;
import webapp.debt.tracker.model.DebtorInfo;

/**
* Generated by Spring Data Generator on 10/03/2020
*/
@Repository
public interface DebtorInfoRepository extends CrudRepository<DebtorInfo, Integer> {

	Optional<DebtorInfo> findByFirstName(String firstName);
	Optional<DebtorInfo> findByEmailAddress(String emailAddress);
//	List<DebtorInfo> findByAppUserAppUserId(Integer appUserId);
}
