package webapp.debt.tracker.model;
// default package

// Generated Mar 10, 2020 7:37:35 PM by Hibernate Tools 5.4.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * AppUser generated by hbm2java
 */
@Entity
@Table(name = "app_user", schema = "debt_tracker")
public class AppUser extends BaseEntity implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private Integer appUserId;
	private String userName;
	private String firstName;
	private String lastName;
	private String emailAddress;
	private String country;
	private String password;
	private byte[] profilePic;
	private Set<DebtInfo> debtInfos = new HashSet<DebtInfo>(0);

	public AppUser() {
	}

	public AppUser(Integer appUserId, String userName, String firstName, String lastName, String emailAddress,
			String country) {
		this.appUserId = appUserId;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.country = country;
	}

	public AppUser(Integer appUserId, String userName, String firstName, String lastName, String emailAddress,
			String country, String password, byte[] profilePic, Set<DebtInfo> debtInfos) {
		this.appUserId = appUserId;
		this.userName = userName;
		this.firstName = firstName;
		this.lastName = lastName;
		this.emailAddress = emailAddress;
		this.country = country;
		this.password = password;
		this.profilePic = profilePic;
		this.debtInfos = debtInfos;
	}

	@Id
	@Column(name = "app_user_id", unique = true, nullable = false)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "appUserSeq")
	@SequenceGenerator(name = "appUserSeq", sequenceName = "app_user_id_seq", allocationSize = 1)
	public Integer getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(Integer appUserId) {
		this.appUserId = appUserId;
	}

	@Column(name = "user_name", nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "first_name", nullable = false, length = 20)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", length = 20)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "email_address", nullable = false, length = 50)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "country", length = 50)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "password", nullable = false)
	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "profile_pic")
	public byte[] getProfilePic() {
		return this.profilePic;
	}

	public void setProfilePic(byte[] profilePic) {
		this.profilePic = profilePic;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "appUser")
	
	public Set<DebtInfo> getDebtInfos() {
		return this.debtInfos;
	}

	public void setDebtInfos(Set<DebtInfo> debtInfos) {
		this.debtInfos = debtInfos;
	}

}
