package webapp.debt.tracker.model;
// default package

// Generated Mar 10, 2020 7:37:35 PM by Hibernate Tools 5.4.12.Final

import java.time.LocalDate;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * DebtPaymentDetail generated by hbm2java
 */
@Entity
@Table(name = "debt_payment_detail", schema = "debt_tracker")
public class DebtPaymentDetail extends BaseEntity implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private Integer debtPaymentDetailId;
	private DebtInfo debtInfo;
	private Integer debtInfoId;
	private Double periodicPaymentAmount;
	private LocalDate estimatedPaymentDate;
	private LocalDate actualPaymentDate;
	private String paymentStatus;

	public DebtPaymentDetail() {
	}

	public DebtPaymentDetail(Integer debtPaymentDetailId, DebtInfo debtInfo, Integer debtInfoId, Double periodicPaymentAmount,
			LocalDate estimatedPaymentDate, LocalDate actualPaymentDate, String paymentStatus) {
		this.debtPaymentDetailId = debtPaymentDetailId;
		this.debtInfo = debtInfo;
		this.debtInfoId =  debtInfoId;
		this.periodicPaymentAmount = periodicPaymentAmount;
		this.estimatedPaymentDate = estimatedPaymentDate;
		this.actualPaymentDate = actualPaymentDate;
		this.paymentStatus = paymentStatus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "debtPaymentDetailSeq")
	@SequenceGenerator(name = "debtPaymentDetailSeq", sequenceName = "debt_payment_detail_id_seq", allocationSize = 1)
	@Column(name = "debt_payment_detail_id", unique = true, nullable = false)
	public Integer getDebtPaymentDetailId() {
		return this.debtPaymentDetailId;
	}

	public void setDebtPaymentDetailId(Integer debtPaymentDetailId) {
		this.debtPaymentDetailId = debtPaymentDetailId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "debt_info_id", nullable = false)
	
	public DebtInfo getDebtInfo() {
		return this.debtInfo;
	}

	public void setDebtInfo(DebtInfo debtInfo) {
		this.debtInfo = debtInfo;
	}

	@Column(name = "debt_info_id", insertable = false, updatable = false)
	public Integer getDebtInfoId() {
		return debtInfoId;
	}

	public void setDebtInfoId(Integer debtInfoId) {
		this.debtInfoId = debtInfoId;
	}

	@Column(name = "periodic_payment_amount", nullable = false, precision = 131089, scale = 0)
	public Double getPeriodicPaymentAmount() {
		return this.periodicPaymentAmount;
	}

	public void setPeriodicPaymentAmount(Double periodicPaymentAmount) {
		this.periodicPaymentAmount = periodicPaymentAmount;
	}

//    @Temporal(TemporalType.LocalDate)
	@Column(name = "estimated_payment_date", nullable = false, length = 13)
	public LocalDate getEstimatedPaymentDate() {
		return this.estimatedPaymentDate;
	}

	public void setEstimatedPaymentDate(LocalDate estimatedPaymentDate) {
		this.estimatedPaymentDate = estimatedPaymentDate;
	}

//    @Temporal(TemporalType.LocalDate)
	@Column(name = "actual_payment_date", length = 13)
	public LocalDate getActualPaymentDate() {
		return this.actualPaymentDate;
	}

	public void setActualPaymentDate(LocalDate actualPaymentDate) {
		this.actualPaymentDate = actualPaymentDate;
	}

	@Column(name = "payment_status", nullable = false)
	public String getPaymentStatus() {
		return this.paymentStatus;
	}

	public void setPaymentStatus(String paymentStatus) {
		this.paymentStatus = paymentStatus;
	}

	@Override
	public String toString() {
		return "DebtPaymentDetail [debtPaymentDetailId=" + debtPaymentDetailId + ", debtInfo=" + debtInfo
				+ ", debtInfoId=" + debtInfoId + ", periodicPaymentAmount=" + periodicPaymentAmount
				+ ", estimatedPaymentDate=" + estimatedPaymentDate + ", actualPaymentDate=" + actualPaymentDate
				+ ", paymentStatus=" + paymentStatus + "]";
	}

	
	
}
