package webapp.debt.tracker.model;
// default package

// Generated Mar 10, 2020 7:37:35 PM by Hibernate Tools 5.4.12.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * DebtInfo generated by hbm2java
 */
@Entity
@Table(name = "debt_info", schema = "debt_tracker")
public class DebtInfo extends BaseEntity implements java.io.Serializable {

	/**
	* 
	*/
	private static final long serialVersionUID = 1L;
	private Integer debtInfoId;
	private AppUser appUser;
	private Integer appUserId;
	private DebtorInfo debtorInfo;
	private Integer debtorInfoId;
	private Double debtAmount;
	private String debtCurrency;
	private Integer numberOfPayments;
	private String paymentFrequencyUnit;
	private String debtConcept;
	private String debtComments;
	private Set<DebtPaymentDetail> debtPaymentDetails = new HashSet<DebtPaymentDetail>(0);

	public DebtInfo() {
	}

	public DebtInfo(Integer debtInfoId, AppUser appUser, DebtorInfo debtorInfo, Double debtAmount, String debtCurrency,
			Integer numberOfPayments, String paymentFrequencyUnit) {
		this.debtInfoId = debtInfoId;
		this.appUser = appUser;
		this.debtorInfo = debtorInfo;
		this.debtAmount = debtAmount;
		this.debtCurrency = debtCurrency;
		this.numberOfPayments = numberOfPayments;
		this.paymentFrequencyUnit = paymentFrequencyUnit;
	}

	public DebtInfo(Integer debtInfoId, AppUser appUser, Integer appUserId, DebtorInfo debtorInfo, Integer debtorInfoId, Double debtAmount, String debtCurrency,
			Integer numberOfPayments, String paymentFrequencyUnit, String debtConcept, String debtComments,Set<DebtPaymentDetail> debtPaymentDetails) {
		this.debtInfoId = debtInfoId;
		this.appUser = appUser;
		this.appUserId = appUserId;
		this.debtorInfo = debtorInfo;
		this.debtorInfoId = debtorInfoId;
		this.debtAmount = debtAmount;
		this.debtCurrency = debtCurrency;
		this.numberOfPayments = numberOfPayments;
		this.paymentFrequencyUnit = paymentFrequencyUnit;
		this.debtPaymentDetails = debtPaymentDetails;
		this.debtConcept = debtConcept;
		this.debtComments = debtComments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "debtInfoSeq")
	@SequenceGenerator(name = "debtInfoSeq", sequenceName = "debt_info_id_seq", allocationSize = 1)
	@Column(name = "debt_info_id", unique = true, nullable = false)
	public Integer getDebtInfoId() {
		return this.debtInfoId;
	}

	public void setDebtInfoId(Integer debtInfoId) {
		this.debtInfoId = debtInfoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "app_user_id", nullable = false)
	
	public AppUser getAppUser() {
		return this.appUser;
	}

	public void setAppUser(AppUser appUser) {
		this.appUser = appUser;
	}
	
	@Column(name = "app_user_id", insertable = false, updatable = false)
	public Integer getAppUserId() {
		return this.appUserId;
	}

	public void setAppUserId(Integer appUserId) {
		this.appUserId = appUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "debtor_data_id", nullable = false)
	
	public DebtorInfo getDebtorInfo() {
		return this.debtorInfo;
	}

	public void setDebtorInfo(DebtorInfo debtorInfo) {
		this.debtorInfo = debtorInfo;
	}
	
	@Column(name = "debtor_data_id", insertable = false, updatable = false)
	public Integer getDebtorInfoId() {
		return this.debtorInfoId;
	}

	public void setDebtorInfoId(Integer debtorInfoId) {
		this.debtorInfoId = debtorInfoId;
	}

	@Column(name = "debt_amount", nullable = false, precision = 131089, scale = 0)
	public Double getDebtAmount() {
		return this.debtAmount;
	}

	public void setDebtAmount(Double debtAmount) {
		this.debtAmount = debtAmount;
	}

	@Column(name = "debt_currency", nullable = false, length = 4)
	public String getDebtCurrency() {
		return this.debtCurrency;
	}

	public void setDebtCurrency(String debtCurrency) {
		this.debtCurrency = debtCurrency;
	}

	@Column(name = "number_of_payments", nullable = false)
	public Integer getNumberOfPayments() {
		return this.numberOfPayments;
	}

	public void setNumberOfPayments(Integer numberOfPayments) {
		this.numberOfPayments = numberOfPayments;
	}

	@Column(name = "payment_frequency_unit", nullable = false)
	public String getPaymentFrequencyUnit() {
		return this.paymentFrequencyUnit;
	}

	public void setPaymentFrequencyUnit(String paymentFrequencyUnit) {
		this.paymentFrequencyUnit = paymentFrequencyUnit;
	}

	@Column(name = "debt_concept", nullable = false)
	public String getDebtConcept() {
		return debtConcept;
	}

	public void setDebtConcept(String debtConcept) {
		this.debtConcept = debtConcept;
	}

	@Column(name = "debt_comments")
	public String getDebtComments() {
		return debtComments;
	}

	public void setDebtComments(String debtComments) {
		this.debtComments = debtComments;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "debtInfo")
	 
	public Set<DebtPaymentDetail> getDebtPaymentDetails() {
		return this.debtPaymentDetails;
	}

	public void setDebtPaymentDetails(Set<DebtPaymentDetail> debtPaymentDetails) {
		this.debtPaymentDetails = debtPaymentDetails;
	}

}
